[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://www.google.com https://maps.google.com https://www.gstatic.com https://www.googletagmanager.com https://www.google-analytics.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.google.com https://*.googleapis.com https://*.gstatic.com https://www.google-analytics.com https://images.unsplash.com; frame-src https://www.google.com; form-action 'self';"

[[redirects]]
  from = "/services/*"
  to = "/services/:splat"
  status = 200

[[redirects]]
  from = "/legal/*"
  to = "/legal/:splat"
  status = 200 